create or replace procedure proc_shangcicb (
  v_number in number
)is
begin
DECLARE
  CURSOR CUR_SHANGCICB IS
  SELECT
    CRUD_TYPE,
    IS_USED,
    ID,
    D_CHAOBIAORQ,
    D_HUICHUANSJ,
    I_BENCICM,
    I_CC,
    I_CHAOBIAON,
    I_CHAOBIAOY,
    I_CHAOJIANSL,
    I_JIDULJ,
    I_KAIZHANGCS,
    I_LINYONGSLSM,
    I_NIANLEIJ,
    I_PINGJUNL1,
    I_PINGJUNL2,
    I_PINGJUNL3,
    I_YUELEIJ,
    I_ZHENSHICM,
    I_ZHUANGTAIBM,
    I_ZHUANTAILXS,
    N_SHANGCIY,
    S_CH,
    S_KEHUID,
    S_ST,
    S_USERID
  FROM TMP_SG_SHANGCICB WHERE IS_USED = 0 and rownum<=v_number;
  V_ID TMP_SG_SHANGCICB.ID%TYPE;
  V_TYPE TMP_SG_SHANGCICB.CRUD_TYPE%TYPE;
  IS_EXIST INTEGER := 0;
BEGIN
FOR V_SHANGCICB IN CUR_SHANGCICB LOOP
  V_ID := V_SHANGCICB.ID;
  V_TYPE := V_SHANGCICB.CRUD_TYPE;
  IF V_TYPE = 1 THEN
    SELECT COUNT(*) INTO IS_EXIST FROM SG_SHANGCICB WHERE S_USERID = V_SHANGCICB.S_USERID;
    IF IS_EXIST = 0 THEN
      -- INSERT DATA
      INSERT INTO SG_SHANGCICB (
        D_CHAOBIAORQ,
        D_HUICHUANSJ,
        I_BENCICM,
        I_CC,
        I_CHAOBIAON,
        I_CHAOBIAOY,
        I_CHAOJIANSL,
        I_JIDULJ,
        I_KAIZHANGCS,
        I_LINYONGSLSM,
        I_NIANLEIJ,
        I_PINGJUNL1,
        I_PINGJUNL2,
        I_PINGJUNL3,
        I_YUELEIJ,
        I_ZHENSHICM,
        I_ZHUANGTAIBM,
        I_ZHUANTAILXS,
        N_SHANGCIY,
        S_CH,
        S_KEHUID,
        S_ST,
        S_USERID
      ) VALUES (
        V_SHANGCICB.D_CHAOBIAORQ,
        V_SHANGCICB.D_HUICHUANSJ,
        V_SHANGCICB.I_BENCICM,
        V_SHANGCICB.I_CC,
        V_SHANGCICB.I_CHAOBIAON,
        V_SHANGCICB.I_CHAOBIAOY,
        V_SHANGCICB.I_CHAOJIANSL,
        V_SHANGCICB.I_JIDULJ,
        V_SHANGCICB.I_KAIZHANGCS,
        V_SHANGCICB.I_LINYONGSLSM,
        V_SHANGCICB.I_NIANLEIJ,
        V_SHANGCICB.I_PINGJUNL1,
        V_SHANGCICB.I_PINGJUNL2,
        V_SHANGCICB.I_PINGJUNL3,
        V_SHANGCICB.I_YUELEIJ,
        V_SHANGCICB.I_ZHENSHICM,
        V_SHANGCICB.I_ZHUANGTAIBM,
        V_SHANGCICB.I_ZHUANTAILXS,
        V_SHANGCICB.N_SHANGCIY,
        V_SHANGCICB.S_CH,
        V_SHANGCICB.S_KEHUID,
        V_SHANGCICB.S_ST,
        V_SHANGCICB.S_USERID
      );
     -- DBMS_OUTPUT.PUT_LINE('添加上次抄表数据');
      -- UPDATE IS_USER
      UPDATE TMP_SG_SHANGCICB SET IS_USED = 1 WHERE ID = V_ID;
    ELSE
      UPDATE TMP_SG_SHANGCICB SET IS_USED = -1 WHERE ID = V_ID;
    END IF;
  ELSIF V_TYPE = 2 THEN
    -- ALTER DATA
    UPDATE SG_SHANGCICB SET
      S_KEHUID = V_SHANGCICB.S_KEHUID,
      S_ST = V_SHANGCICB.S_ST,
      S_CH = V_SHANGCICB.S_CH,
      S_USERID = V_SHANGCICB.S_USERID,
      I_ZHUANTAILXS = V_SHANGCICB.I_ZHUANTAILXS,
      I_BENCICM = V_SHANGCICB.I_BENCICM,
      I_ZHUANGTAIBM = V_SHANGCICB.I_ZHUANGTAIBM,
      D_CHAOBIAORQ = V_SHANGCICB.D_CHAOBIAORQ,
      I_CHAOBIAON = V_SHANGCICB.I_CHAOBIAON,
      I_CHAOBIAOY = V_SHANGCICB.I_CHAOBIAOY,
      I_CC = V_SHANGCICB.I_CC,
      I_CHAOJIANSL = V_SHANGCICB.I_CHAOJIANSL,
      I_KAIZHANGCS = V_SHANGCICB.I_KAIZHANGCS,
      I_PINGJUNL1 = V_SHANGCICB.I_PINGJUNL1,
      I_PINGJUNL2 = V_SHANGCICB.I_PINGJUNL2,
      I_PINGJUNL3 = V_SHANGCICB.I_PINGJUNL3,
      I_YUELEIJ = V_SHANGCICB.I_YUELEIJ,
      I_JIDULJ = V_SHANGCICB.I_JIDULJ,
      I_NIANLEIJ = V_SHANGCICB.I_NIANLEIJ,
      N_SHANGCIY = V_SHANGCICB.N_SHANGCIY,
      I_ZHENSHICM = V_SHANGCICB.I_ZHENSHICM,
      I_LINYONGSLSM = V_SHANGCICB.I_LINYONGSLSM,
      D_HUICHUANSJ = V_SHANGCICB.D_HUICHUANSJ
    WHERE S_USERID = V_SHANGCICB.S_USERID; -- AND I_CHAOBIAON = V_SHANGCICB.I_CHAOBIAON AND I_CHAOBIAOY = V_SHANGCICB.I_CHAOBIAOY;
   -- DBMS_OUTPUT.PUT_LINE('修改上次抄表数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_SHANGCICB SET IS_USED = 1 WHERE ID = V_ID;
  ELSIF V_TYPE = 3 THEN
    -- DELETE DATA
    DELETE FROM SG_SHANGCICB WHERE S_USERID = V_SHANGCICB.S_USERID; -- AND I_CHAOBIAON = V_SHANGCICB.I_CHAOBIAON AND I_CHAOBIAOY = V_SHANGCICB.I_CHAOBIAOY;
   -- DBMS_OUTPUT.PUT_LINE('删除上次抄表数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_SHANGCICB SET IS_USED = 1 WHERE ID = V_ID;
  ELSE
    DBMS_OUTPUT.PUT_LINE('数据不可用或没有对应的数据操作类型CRUD_TYPE' || V_SHANGCICB.CRUD_TYPE);
  END IF;
END LOOP;
--DELETE  TMP_SG_SHANGCICB  where sysdate-7 > d_huichuansj AND IS_USED =1;
end;
end;
/
