create or replace procedure proc_shuibiaokj (
  v_number in number
)is
begin
DECLARE
  CURSOR CUR_SHUIBIAOKJ IS
  SELECT
    CRUD_TYPE,
    IS_USED,
    ID,
    D_CAOZUOSJ,
    D_HUICHUANSJ,
    I_DINGHUANZQ,
    I_JLZT,
    I_KOUJINGSZ,
    I_LIANGCHENG,
    I_QIANGJIANZQ,
    I_QISUANDS,
    N_LIANGDI,
    N_LIANGGAO,
    S_BEIZHU,
    S_CAOZUOR,
    S_KOUJINGBH,
    S_KOUJINGMC
  FROM TMP_SG_SHUIBIAOKJ WHERE IS_USED = 0 and rownum<=v_number;
  V_ID TMP_SG_SHUIBIAOKJ.ID%TYPE;
  V_TYPE TMP_SG_SHUIBIAOKJ.CRUD_TYPE%TYPE;
  IS_EXIST INTEGER := 0;
BEGIN
FOR V_SHUIBIAOKJ IN CUR_SHUIBIAOKJ LOOP
  V_ID := V_SHUIBIAOKJ.ID;
  V_TYPE := V_SHUIBIAOKJ.CRUD_TYPE;
  IF V_TYPE = 1 THEN
    SELECT COUNT(*) INTO IS_EXIST FROM SG_SHUIBIAOKJ WHERE S_KOUJINGBH = V_SHUIBIAOKJ.S_KOUJINGBH;
    IF IS_EXIST = 0 THEN
      -- INSERT DATA
      INSERT INTO SG_SHUIBIAOKJ (
        D_CAOZUOSJ,
        D_HUICHUANSJ,
        I_DINGHUANZQ,
        I_JLZT,
        I_KOUJINGSZ,
        I_LIANGCHENG,
        I_QIANGJIANZQ,
        I_QISUANDS,
        N_LIANGDI,
        N_LIANGGAO,
        S_BEIZHU,
        S_CAOZUOR,
        S_KOUJINGBH,
        S_KOUJINGMC
      ) VALUES (
        V_SHUIBIAOKJ.D_CAOZUOSJ,
        V_SHUIBIAOKJ.D_HUICHUANSJ,
        V_SHUIBIAOKJ.I_DINGHUANZQ,
        V_SHUIBIAOKJ.I_JLZT,
        V_SHUIBIAOKJ.I_KOUJINGSZ,
        V_SHUIBIAOKJ.I_LIANGCHENG,
        V_SHUIBIAOKJ.I_QIANGJIANZQ,
        V_SHUIBIAOKJ.I_QISUANDS,
        V_SHUIBIAOKJ.N_LIANGDI,
        V_SHUIBIAOKJ.N_LIANGGAO,
        V_SHUIBIAOKJ.S_BEIZHU,
        V_SHUIBIAOKJ.S_CAOZUOR,
        V_SHUIBIAOKJ.S_KOUJINGBH,
        V_SHUIBIAOKJ.S_KOUJINGMC
      );
   --   DBMS_OUTPUT.PUT_LINE('添加水表口径数据');
      -- UPDATE IS_USER
      UPDATE TMP_SG_SHUIBIAOKJ SET IS_USED = 1 WHERE ID = V_ID;
    ELSE
      UPDATE TMP_SG_SHUIBIAOKJ SET IS_USED = -1 WHERE ID = V_ID;
    END IF;
  ELSIF V_TYPE = 2 THEN
    -- ALTER DATA
    UPDATE SG_SHUIBIAOKJ SET
      S_KOUJINGBH = V_SHUIBIAOKJ.S_KOUJINGBH,
      S_KOUJINGMC = V_SHUIBIAOKJ.S_KOUJINGMC,
      I_KOUJINGSZ = V_SHUIBIAOKJ.I_KOUJINGSZ,
      I_QIANGJIANZQ = V_SHUIBIAOKJ.I_QIANGJIANZQ,
      I_DINGHUANZQ = V_SHUIBIAOKJ.I_DINGHUANZQ,
      I_LIANGCHENG = V_SHUIBIAOKJ.I_LIANGCHENG,
      N_LIANGDI = V_SHUIBIAOKJ.N_LIANGDI,
      N_LIANGGAO = V_SHUIBIAOKJ.N_LIANGGAO,
      I_JLZT = V_SHUIBIAOKJ.I_JLZT,
      I_QISUANDS = V_SHUIBIAOKJ.I_QISUANDS,
      S_BEIZHU = V_SHUIBIAOKJ.S_BEIZHU,
      S_CAOZUOR = V_SHUIBIAOKJ.S_CAOZUOR,
      D_CAOZUOSJ = V_SHUIBIAOKJ.D_CAOZUOSJ,
      D_HUICHUANSJ = V_SHUIBIAOKJ.D_HUICHUANSJ
    WHERE S_KOUJINGBH = V_SHUIBIAOKJ.S_KOUJINGBH;
   -- DBMS_OUTPUT.PUT_LINE('修改水表口径数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_SHUIBIAOKJ SET IS_USED = 1 WHERE ID = V_ID;
  ELSIF V_TYPE = 3 THEN
    -- DELETE DATA
    DELETE FROM SG_SHUIBIAOKJ WHERE S_KOUJINGBH = V_SHUIBIAOKJ.S_KOUJINGBH;
    --DBMS_OUTPUT.PUT_LINE('删除水表口径数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_SHUIBIAOKJ SET IS_USED = 1 WHERE ID = V_ID;
  ELSE
    DBMS_OUTPUT.PUT_LINE('数据不可用或没有对应的数据操作类型CRUD_TYPE' || V_SHUIBIAOKJ.CRUD_TYPE);
  END IF;
END LOOP;
	--DELETE  TMP_SG_SHUIBIAOKJ  where sysdate-7 > d_huichuansj AND IS_USED =1;
end;
end;
/
