create or replace procedure proc_jiaofeixx (
	v_number in number
)as
begin
	DECLARE
  CURSOR CUR_JIAOFEIXX IS
  SELECT
    CRUD_TYPE,
    IS_USED,
    ID,
    D_CHAOBIAORQ,
    D_HUICHUANSJ,
    D_KAIZHANG,
    D_SHOUFEIRQ,
    D_XIAOZHANGRQ,
    I_BENCICM,
    I_KAIHANGSL,
    I_KAIZHANGN,
    I_KAIZHANGY,
    I_SHANGCICM,
    N_DANJIA,
    N_SHISHOUZNJ,
    N_ZHANGDANJE,
    S_DZ,
    S_JH,
    S_KEHUID,
    S_SHOUFEIBM,
    S_SHOUFEITJ,
    S_SHOUFEIY,
    S_USERID,
    S_XIAOZHANGFS,
    I_SHOUFEIHZBH,
    I_SHOUFEIPH,
    I_FEEID
  FROM TMP_SG_JIAOFEIXX WHERE IS_USED = 0 and rownum<=v_number;
  V_ID TMP_SG_JIAOFEIXX.ID%TYPE;
  V_TYPE TMP_SG_JIAOFEIXX.CRUD_TYPE%TYPE;
  IS_EXIST INTEGER := 0;
BEGIN
FOR V_JIAOFEIXX IN CUR_JIAOFEIXX LOOP
  V_ID := V_JIAOFEIXX.ID;
  V_TYPE := V_JIAOFEIXX.CRUD_TYPE;
  IF V_TYPE = 1 THEN
    SELECT COUNT(*) INTO IS_EXIST FROM SG_JIAOFEIXX WHERE S_USERID = V_JIAOFEIXX.S_USERID AND I_SHOUFEIHZBH = V_JIAOFEIXX.I_SHOUFEIHZBH AND I_SHOUFEIPH = V_JIAOFEIXX.I_SHOUFEIPH AND I_FEEID = V_JIAOFEIXX.I_FEEID;
    IF IS_EXIST = 0 THEN
      -- INSERT DATA
      INSERT INTO SG_JIAOFEIXX
      (
        D_CHAOBIAORQ,
        D_HUICHUANSJ,
        D_KAIZHANG,
        D_SHOUFEIRQ,
        D_XIAOZHANGRQ,
        I_BENCICM,
        I_KAIHANGSL,
        I_KAIZHANGN,
        I_KAIZHANGY,
        I_SHANGCICM,
        N_DANJIA,
        N_SHISHOUZNJ,
        N_ZHANGDANJE,
        S_DZ,
        S_JH,
        S_KEHUID,
        S_SHOUFEIBM,
        S_SHOUFEITJ,
        S_SHOUFEIY,
        S_USERID,
        S_XIAOZHANGFS,
        I_SHOUFEIHZBH,
        I_SHOUFEIPH,
        I_FEEID
      ) VALUES
      (
        V_JIAOFEIXX.D_CHAOBIAORQ,
        V_JIAOFEIXX.D_HUICHUANSJ,
        V_JIAOFEIXX.D_KAIZHANG,
        V_JIAOFEIXX.D_SHOUFEIRQ,
        V_JIAOFEIXX.D_XIAOZHANGRQ,
        V_JIAOFEIXX.I_BENCICM,
        V_JIAOFEIXX.I_KAIHANGSL,
        V_JIAOFEIXX.I_KAIZHANGN,
        V_JIAOFEIXX.I_KAIZHANGY,
        V_JIAOFEIXX.I_SHANGCICM,
        V_JIAOFEIXX.N_DANJIA,
        V_JIAOFEIXX.N_SHISHOUZNJ,
        V_JIAOFEIXX.N_ZHANGDANJE,
        V_JIAOFEIXX.S_DZ,
        V_JIAOFEIXX.S_JH,
        V_JIAOFEIXX.S_KEHUID,
        V_JIAOFEIXX.S_SHOUFEIBM,
        V_JIAOFEIXX.S_SHOUFEITJ,
        V_JIAOFEIXX.S_SHOUFEIY,
        V_JIAOFEIXX.S_USERID,
        V_JIAOFEIXX.S_XIAOZHANGFS,
        V_JIAOFEIXX.I_SHOUFEIHZBH,
        V_JIAOFEIXX.I_SHOUFEIPH,
        V_JIAOFEIXX.I_FEEID
      );
      --DBMS_OUTPUT.PUT_LINE('添加缴费数据');
      -- UPDATE IS_USER
      UPDATE TMP_SG_JIAOFEIXX SET IS_USED = 1 WHERE ID = V_ID;
    ELSE
      UPDATE TMP_SG_JIAOFEIXX SET IS_USED = -1 WHERE ID = V_ID;
    END IF;
  ELSIF V_TYPE = 2 THEN
    -- ALTER DATA
    UPDATE SG_JIAOFEIXX SET
      S_USERID = V_JIAOFEIXX.S_USERID,
      S_KEHUID = V_JIAOFEIXX.S_KEHUID,
      I_BENCICM = V_JIAOFEIXX.I_BENCICM,
      I_SHANGCICM = V_JIAOFEIXX.I_SHANGCICM,
      S_JH = V_JIAOFEIXX.S_JH,
      S_SHOUFEITJ = V_JIAOFEIXX.S_SHOUFEITJ,
      S_XIAOZHANGFS = V_JIAOFEIXX.S_XIAOZHANGFS,
      I_KAIZHANGN = V_JIAOFEIXX.I_KAIZHANGN,
      I_KAIZHANGY = V_JIAOFEIXX.I_KAIZHANGY,
      N_DANJIA = V_JIAOFEIXX.N_DANJIA,
      S_SHOUFEIY = V_JIAOFEIXX.S_SHOUFEIY,
      S_SHOUFEIBM = V_JIAOFEIXX.S_SHOUFEIBM,
      S_DZ = V_JIAOFEIXX.S_DZ,
      N_ZHANGDANJE = V_JIAOFEIXX.N_ZHANGDANJE,
      N_SHISHOUZNJ = V_JIAOFEIXX.N_SHISHOUZNJ,
      I_KAIHANGSL = V_JIAOFEIXX.I_KAIHANGSL,
      D_CHAOBIAORQ = V_JIAOFEIXX.D_CHAOBIAORQ,
      D_SHOUFEIRQ = V_JIAOFEIXX.D_SHOUFEIRQ,
      D_KAIZHANG = V_JIAOFEIXX.D_KAIZHANG,
      D_XIAOZHANGRQ = V_JIAOFEIXX.D_XIAOZHANGRQ,
      D_HUICHUANSJ = V_JIAOFEIXX.D_HUICHUANSJ,
      I_SHOUFEIHZBH = V_JIAOFEIXX.I_SHOUFEIHZBH,
      I_SHOUFEIPH = V_JIAOFEIXX.I_SHOUFEIPH,
      I_FEEID = V_JIAOFEIXX.I_FEEID
    WHERE S_USERID = V_JIAOFEIXX.S_USERID AND I_SHOUFEIHZBH = V_JIAOFEIXX.I_SHOUFEIHZBH AND I_SHOUFEIPH = V_JIAOFEIXX.I_SHOUFEIPH AND I_FEEID = V_JIAOFEIXX.I_FEEID;
    --DBMS_OUTPUT.PUT_LINE('修改缴费数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_JIAOFEIXX SET IS_USED = 1 WHERE ID = V_ID;
  ELSIF V_TYPE = 3 THEN
    -- DELETE DATA
    DELETE FROM SG_JIAOFEIXX WHERE S_USERID = V_JIAOFEIXX.S_USERID AND I_SHOUFEIHZBH = V_JIAOFEIXX.I_SHOUFEIHZBH AND I_SHOUFEIPH = V_JIAOFEIXX.I_SHOUFEIPH AND I_FEEID = V_JIAOFEIXX.I_FEEID;
    --DBMS_OUTPUT.PUT_LINE('删除缴费数据');
    -- UPDATE IS_USER
    UPDATE TMP_SG_JIAOFEIXX SET IS_USED = 1 WHERE ID = V_ID;
  ELSE
    DBMS_OUTPUT.PUT_LINE('没有对应的数据操作类型CRUD_TYPE' || V_JIAOFEIXX.CRUD_TYPE);
  END IF;
END LOOP;
--	DELETE  TMP_SG_JIAOFEIXX where sysdate-7>d_huichuansj AND IS_USED =1;
END;
end;
/
